export const dataMock = [
  {
    key: "1",
    name: "John Brown",
    url: "https://admin.joseonofre.vercel.app/",
    owner: "xiao",
    type: "private",
    approver: "jack",
    description: "lorem ipsum dolor sit amet",
    age: 32,
    address: "New York No. 1 Lake Park",
    tags: ["nice", "developer"],
  },
  {
    key: "2",
    name: "Jim Green",
    url: "https://admin.joseonofre.vercel.app/",
    owner: "xiao",
    type: "private",
    approver: "jack",
    description: "lorem ipsum dolor sit amet",
    age: 42,
    address: "London No. 1 Lake Park",
    tags: ["loser"],
  },
  {
    key: "3",
    name: "Joe Black",
    url: "https://admin.joseonofre.vercel.app/",
    owner: "xiao",
    type: "private",
    approver: "jack",
    description: "lorem ipsum dolor sit amet",
    age: 32,
    address: "Sidney No. 1 Lake Park",
    tags: ["cool", "teacher"],
  },
  {
    key: "4",
    name: "Disabled User",
    url: "https://admin.joseonofre.vercel.app/",
    owner: "xiao",
    type: "private",
    approver: "jack",
    description: "lorem ipsum dolor sit amet",
    age: 99,
    address: "Sidney No. 1 Lake Park",
    tags: ["nice", "developer"],
  },
];
